// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.1
// source: proxy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RequestModClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*RequestModClientMessage_Register
	//	*RequestModClientMessage_ModifiedRequest
	Msg           isRequestModClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestModClientMessage) Reset() {
	*x = RequestModClientMessage{}
	mi := &file_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestModClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestModClientMessage) ProtoMessage() {}

func (x *RequestModClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestModClientMessage.ProtoReflect.Descriptor instead.
func (*RequestModClientMessage) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *RequestModClientMessage) GetMsg() isRequestModClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RequestModClientMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Msg.(*RequestModClientMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *RequestModClientMessage) GetModifiedRequest() *HttpRequest {
	if x != nil {
		if x, ok := x.Msg.(*RequestModClientMessage_ModifiedRequest); ok {
			return x.ModifiedRequest
		}
	}
	return nil
}

type isRequestModClientMessage_Msg interface {
	isRequestModClientMessage_Msg()
}

type RequestModClientMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type RequestModClientMessage_ModifiedRequest struct {
	ModifiedRequest *HttpRequest `protobuf:"bytes,2,opt,name=modifiedRequest,proto3,oneof"`
}

func (*RequestModClientMessage_Register) isRequestModClientMessage_Msg() {}

func (*RequestModClientMessage_ModifiedRequest) isRequestModClientMessage_Msg() {}

type ResponseModClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ResponseModClientMessage_Register
	//	*ResponseModClientMessage_ModifiedResponse
	Msg           isResponseModClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseModClientMessage) Reset() {
	*x = ResponseModClientMessage{}
	mi := &file_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseModClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseModClientMessage) ProtoMessage() {}

func (x *ResponseModClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseModClientMessage.ProtoReflect.Descriptor instead.
func (*ResponseModClientMessage) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseModClientMessage) GetMsg() isResponseModClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ResponseModClientMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Msg.(*ResponseModClientMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ResponseModClientMessage) GetModifiedResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Msg.(*ResponseModClientMessage_ModifiedResponse); ok {
			return x.ModifiedResponse
		}
	}
	return nil
}

type isResponseModClientMessage_Msg interface {
	isResponseModClientMessage_Msg()
}

type ResponseModClientMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ResponseModClientMessage_ModifiedResponse struct {
	ModifiedResponse *HttpResponse `protobuf:"bytes,2,opt,name=modifiedResponse,proto3,oneof"`
}

func (*ResponseModClientMessage_Register) isResponseModClientMessage_Msg() {}

func (*ResponseModClientMessage_ModifiedResponse) isResponseModClientMessage_Msg() {}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *Register) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// HttpRequest represents an HTTP request.
type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Headers       []*Header              `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *HttpRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// HttpResponse represents an HTTP response.
type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *HttpResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Config struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DbFile                  string                 `protobuf:"bytes,1,opt,name=db_file,json=dbFile,proto3" json:"db_file,omitempty"`
	PrintLogs               bool                   `protobuf:"varint,2,opt,name=print_logs,json=printLogs,proto3" json:"print_logs,omitempty"`
	SaveDir                 string                 `protobuf:"bytes,3,opt,name=save_dir,json=saveDir,proto3" json:"save_dir,omitempty"`
	ScopeDomainRe           string                 `protobuf:"bytes,4,opt,name=scopeDomainRe,proto3" json:"scopeDomainRe,omitempty"`
	ScopeExcludedExtensions []string               `protobuf:"bytes,5,rep,name=scopeExcludedExtensions,proto3" json:"scopeExcludedExtensions,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *Config) GetDbFile() string {
	if x != nil {
		return x.DbFile
	}
	return ""
}

func (x *Config) GetPrintLogs() bool {
	if x != nil {
		return x.PrintLogs
	}
	return false
}

func (x *Config) GetSaveDir() string {
	if x != nil {
		return x.SaveDir
	}
	return ""
}

func (x *Config) GetScopeDomainRe() string {
	if x != nil {
		return x.ScopeDomainRe
	}
	return ""
}

func (x *Config) GetScopeExcludedExtensions() []string {
	if x != nil {
		return x.ScopeExcludedExtensions
	}
	return nil
}

type Null struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Null) Reset() {
	*x = Null{}
	mi := &file_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{7}
}

var File_proxy_proto protoreflect.FileDescriptor

const file_proxy_proto_rawDesc = "" +
	"\n" +
	"\vproxy.proto\x12\x05proxy\"2\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x8f\x01\n" +
	"\x17RequestModClientMessage\x12-\n" +
	"\bregister\x18\x01 \x01(\v2\x0f.proxy.RegisterH\x00R\bregister\x12>\n" +
	"\x0fmodifiedRequest\x18\x02 \x01(\v2\x12.proxy.HttpRequestH\x00R\x0fmodifiedRequestB\x05\n" +
	"\x03msg\"\x93\x01\n" +
	"\x18ResponseModClientMessage\x12-\n" +
	"\bregister\x18\x01 \x01(\v2\x0f.proxy.RegisterH\x00R\bregister\x12A\n" +
	"\x10modifiedResponse\x18\x02 \x01(\v2\x13.proxy.HttpResponseH\x00R\x10modifiedResponseB\x05\n" +
	"\x03msg\"\x1e\n" +
	"\bRegister\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x84\x01\n" +
	"\vHttpRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12'\n" +
	"\aheaders\x18\x04 \x03(\v2\r.proxy.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\"|\n" +
	"\fHttpResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12'\n" +
	"\aheaders\x18\x03 \x03(\v2\r.proxy.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"\xbb\x01\n" +
	"\x06Config\x12\x17\n" +
	"\adb_file\x18\x01 \x01(\tR\x06dbFile\x12\x1d\n" +
	"\n" +
	"print_logs\x18\x02 \x01(\bR\tprintLogs\x12\x19\n" +
	"\bsave_dir\x18\x03 \x01(\tR\asaveDir\x12$\n" +
	"\rscopeDomainRe\x18\x04 \x01(\tR\rscopeDomainRe\x128\n" +
	"\x17scopeExcludedExtensions\x18\x05 \x03(\tR\x17scopeExcludedExtensions\"\x06\n" +
	"\x04Null2\xd5\x03\n" +
	"\fProxyService\x124\n" +
	"\tRequestIn\x12\x0f.proxy.Register\x1a\x12.proxy.HttpRequest\"\x000\x01\x12F\n" +
	"\n" +
	"RequestMod\x12\x1e.proxy.RequestModClientMessage\x1a\x12.proxy.HttpRequest\"\x00(\x010\x01\x125\n" +
	"\n" +
	"RequestOut\x12\x0f.proxy.Register\x1a\x12.proxy.HttpRequest\"\x000\x01\x126\n" +
	"\n" +
	"ResponseIn\x12\x0f.proxy.Register\x1a\x13.proxy.HttpResponse\"\x000\x01\x12I\n" +
	"\vResponseMod\x12\x1f.proxy.ResponseModClientMessage\x1a\x13.proxy.HttpResponse\"\x00(\x010\x01\x127\n" +
	"\vResponseOut\x12\x0f.proxy.Register\x1a\x13.proxy.HttpResponse\"\x000\x01\x12)\n" +
	"\tSetConfig\x12\r.proxy.Config\x1a\v.proxy.Null\"\x00\x12)\n" +
	"\tGetConfig\x12\v.proxy.Null\x1a\r.proxy.Config\"\x00B6Z4github.com/artilugio0/efin-proxy/internal/grpc/protob\x06proto3"

var (
	file_proxy_proto_rawDescOnce sync.Once
	file_proxy_proto_rawDescData []byte
)

func file_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)))
	})
	return file_proxy_proto_rawDescData
}

var file_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proxy_proto_goTypes = []any{
	(*Header)(nil),                   // 0: proxy.Header
	(*RequestModClientMessage)(nil),  // 1: proxy.RequestModClientMessage
	(*ResponseModClientMessage)(nil), // 2: proxy.ResponseModClientMessage
	(*Register)(nil),                 // 3: proxy.Register
	(*HttpRequest)(nil),              // 4: proxy.HttpRequest
	(*HttpResponse)(nil),             // 5: proxy.HttpResponse
	(*Config)(nil),                   // 6: proxy.Config
	(*Null)(nil),                     // 7: proxy.Null
}
var file_proxy_proto_depIdxs = []int32{
	3,  // 0: proxy.RequestModClientMessage.register:type_name -> proxy.Register
	4,  // 1: proxy.RequestModClientMessage.modifiedRequest:type_name -> proxy.HttpRequest
	3,  // 2: proxy.ResponseModClientMessage.register:type_name -> proxy.Register
	5,  // 3: proxy.ResponseModClientMessage.modifiedResponse:type_name -> proxy.HttpResponse
	0,  // 4: proxy.HttpRequest.headers:type_name -> proxy.Header
	0,  // 5: proxy.HttpResponse.headers:type_name -> proxy.Header
	3,  // 6: proxy.ProxyService.RequestIn:input_type -> proxy.Register
	1,  // 7: proxy.ProxyService.RequestMod:input_type -> proxy.RequestModClientMessage
	3,  // 8: proxy.ProxyService.RequestOut:input_type -> proxy.Register
	3,  // 9: proxy.ProxyService.ResponseIn:input_type -> proxy.Register
	2,  // 10: proxy.ProxyService.ResponseMod:input_type -> proxy.ResponseModClientMessage
	3,  // 11: proxy.ProxyService.ResponseOut:input_type -> proxy.Register
	6,  // 12: proxy.ProxyService.SetConfig:input_type -> proxy.Config
	7,  // 13: proxy.ProxyService.GetConfig:input_type -> proxy.Null
	4,  // 14: proxy.ProxyService.RequestIn:output_type -> proxy.HttpRequest
	4,  // 15: proxy.ProxyService.RequestMod:output_type -> proxy.HttpRequest
	4,  // 16: proxy.ProxyService.RequestOut:output_type -> proxy.HttpRequest
	5,  // 17: proxy.ProxyService.ResponseIn:output_type -> proxy.HttpResponse
	5,  // 18: proxy.ProxyService.ResponseMod:output_type -> proxy.HttpResponse
	5,  // 19: proxy.ProxyService.ResponseOut:output_type -> proxy.HttpResponse
	7,  // 20: proxy.ProxyService.SetConfig:output_type -> proxy.Null
	6,  // 21: proxy.ProxyService.GetConfig:output_type -> proxy.Config
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proxy_proto_init() }
func file_proxy_proto_init() {
	if File_proxy_proto != nil {
		return
	}
	file_proxy_proto_msgTypes[1].OneofWrappers = []any{
		(*RequestModClientMessage_Register)(nil),
		(*RequestModClientMessage_ModifiedRequest)(nil),
	}
	file_proxy_proto_msgTypes[2].OneofWrappers = []any{
		(*ResponseModClientMessage_Register)(nil),
		(*ResponseModClientMessage_ModifiedResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proto_depIdxs,
		MessageInfos:      file_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proto = out.File
	file_proxy_proto_goTypes = nil
	file_proxy_proto_depIdxs = nil
}
